name = "chatgpt-api"
main = "src/index.js"
compatibility_date = "2023-03-03"
usage_model = "bundled"
env = { }
kv_namespaces = [
  { binding = "kv", id = "e655de7245b44d238aa3fd100c1d37bf" }
]

[triggers]
crons = [ ]
